/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Filipe
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
         normal_img.setVisible(false);
        obesoleve_img1.setVisible(false);
        abaixo_img1.setVisible(false);
        obesomorbi_img1.setVisible(false);
        sobrepeso_img.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resul_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alt_txt1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        peso_txt1 = new javax.swing.JTextField();
        clear_BTN = new javax.swing.JButton();
        fecha_BTN = new javax.swing.JButton();
        sobrepeso_img = new javax.swing.JLabel();
        normal_img = new javax.swing.JLabel();
        abaixo_img1 = new javax.swing.JLabel();
        obesoleve_img1 = new javax.swing.JLabel();
        obesomorbi_img1 = new javax.swing.JLabel();
        calc_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo (1).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 140, 90);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Resultado:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 250, 127, 21);

        resul_txt.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jPanel1.add(resul_txt);
        resul_txt.setBounds(170, 240, 160, 40);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Digite a sua Altura:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 170, 21);

        alt_txt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(alt_txt1);
        alt_txt1.setBounds(170, 140, 160, 23);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Digite o seu peso:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 190, 160, 21);

        peso_txt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(peso_txt1);
        peso_txt1.setBounds(170, 190, 160, 23);

        clear_BTN.setText("Limpar Campos");
        clear_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(clear_BTN);
        clear_BTN.setBounds(10, 360, 130, 25);

        fecha_BTN.setBackground(new java.awt.Color(255, 51, 51));
        fecha_BTN.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        fecha_BTN.setForeground(new java.awt.Color(255, 255, 255));
        fecha_BTN.setText("X");
        fecha_BTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fecha_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(fecha_BTN);
        fecha_BTN.setBounds(10, 10, 60, 30);

        sobrepeso_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sobrepeso.png"))); // NOI18N
        jPanel1.add(sobrepeso_img);
        sobrepeso_img.setBounds(410, 20, 140, 330);

        normal_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/normal.png"))); // NOI18N
        jPanel1.add(normal_img);
        normal_img.setBounds(420, 30, 105, 310);

        abaixo_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/abaixo do peso.png"))); // NOI18N
        jPanel1.add(abaixo_img1);
        abaixo_img1.setBounds(410, 20, 140, 330);

        obesoleve_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/obesidade leve.png"))); // NOI18N
        jPanel1.add(obesoleve_img1);
        obesoleve_img1.setBounds(400, 10, 140, 330);

        obesomorbi_img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/obesidade morbida.png"))); // NOI18N
        jPanel1.add(obesomorbi_img1);
        obesomorbi_img1.setBounds(390, 20, 140, 330);

        calc_BTN.setText("Calcular IMC");
        calc_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(calc_BTN);
        calc_BTN.setBounds(10, 320, 130, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(533, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fecha_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_BTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fecha_BTNActionPerformed

    private void clear_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_BTNActionPerformed
        // TODO add your handling code here:
        Controller.Calcula_DAO.limpa();
    }//GEN-LAST:event_clear_BTNActionPerformed

    private void calc_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_BTNActionPerformed
        // TODO add your handling code here:
        Controller.Calcula_DAO.imc();
    }//GEN-LAST:event_calc_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel abaixo_img1;
    public static javax.swing.JTextField alt_txt1;
    private javax.swing.JButton calc_BTN;
    private javax.swing.JButton clear_BTN;
    private javax.swing.JButton fecha_BTN;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel normal_img;
    public static javax.swing.JLabel obesoleve_img1;
    public static javax.swing.JLabel obesomorbi_img1;
    public static javax.swing.JTextField peso_txt1;
    public static javax.swing.JTextField resul_txt;
    public static javax.swing.JLabel sobrepeso_img;
    // End of variables declaration//GEN-END:variables
}
